require 'erb'
require_relative 'job'

name = "matlab_test_" # jobs name

desc "make a config file"
task :make_job do
  Rake::Task["clean"].invoke
  num = 0
  for num in  1..10
    name_make = "matlab_test_" 
    job = Job.new # make a job object
    job.name = name_make.concat(num.to_s) # add a number to it

    slurm_template = File.read("test.slurm.erb") # read in template

    file_name = job.name # file name
    file_name.concat(".slurm")
    File.open(file_name, "w") do |f|
      f.write ERB.new(slurm_template).result(binding)
    end
  end

end

desc "remove written file"
task :clean do
  for num in  1..10
    file_name = "matlab_test_" 
    file_name.concat(num.to_s)
    file_name.concat(".slurm")
    File.delete(file_name) if File.exists? file_name
  end
end
