%% JX_16QAM_v7 is a sample code develped on June, 2018
%  developed on R2017b  
%  Support the following cases: 
%           PDM optical signal, WDM channels, 
%           Multiple regular single fiber spans,
%           ideal constant gain amplifiers, 
%           accumulate CD is removed by a pseudofiber,
%           no PMD, 
%  requires:   matlab communication system toolbox and 
%      prbs.m, bitsGenerator.m, transmitterField_v3.m 
%      create_uniqueFiled.m, setChannelWavelengths.m 
%      hybrid_span_v1.m, phaseEqualizer_v1.m,getSignalPower.m, getSignalPower_v1
%      createDirectoryForResults.m, 
% JX_16QAM_v7 support uniform, PRBS, and PRSS pattern.  The data
% sequences is generated once and then set them into different power and
% pass through the fiber link. hybrid_span_v1.m support hybrid fiber span
% with first segement span is QSM with MPI and second span is regular SMF.
% MPI is added at the end of fiber link. TransmitterField_v3 supports
% PRSS4096, PRBS, and uniform pattern and calibrates the transmiting data
% power to 1 mW ( excluding the extra samples generated by filter).
%
clear all
close all
clc

tic;   % start  a timer

laserPowerdBmArray=-6:5;
n=length(laserPowerdBmArray)
QdB = [];
parfor i = 1:n
    QdB(i) = qsmf_simulation_fft2(laserPowerdBmArray(i));
end

% calculate running time

toc;    % stop the timer 

results =[laserPowerdBmArray',QdB'];
results

% results=[laserPowerdBmArray,QdB];
% params = [totalLength,spanLength,segmentLength_1,percComp];
% filename = sprintf('results_%s_%d_%s_%d_%s_%d_%s_%d.txt','Aeff',link.fiber1.aeff_1,'spanLength',spanLength,'comp',percComp,'ls1',segmentLength_1);
% fid = fopen(filename, 'a+');
% fprintf(fid, '%s %s %s %s\n','totalLength','spanLength','segmentLength_1','percComp');
% fprintf(fid, '%d %d %d %d\n', params);
% fprintf(fid, '%s %s\n','Power (dBm)','Q (dB)');
% fprintf(fid, '%d %d\n', results);
% fclose(fid);

